### ISSUE TITLE
Defragment the file system (not files) 

### ISSUE THREAD

**Issue by zvezdochiot** [i-rinat/reiserfs-defrag#3]
It is interesting to defragment the file tables (ReiserFS) without defragmenting the files themselves.

**Comment by i-rinat** [comment]
I doubt it would be of any use. It will definitely first time speed-up directory accesses, but since files will remain fragmented, overall performance will not be changed.

I think it's possible to insert `return RFSD_OK;` here: https://github.com/i-rinat/reiserfs-defrag/blob/ebecfcbd079b099d70ff6304fd8eb91284dab3ca/defrag.cpp#L85. And that will turn "tree-through" mode into approximately what you are trying to achieve. Only internal nodes will be moved though. Leaves will remain where they were.

**Comment by i-rinat** [comment]
I do not understand what are you trying to say.

**Comment by zvezdochiot** [comment]
I want to optimize the file table
